"""High-level entry points for the MT5 toolkit.

The repository historically exposed dozens of standalone scripts at the project
root (for example ``train.py`` and ``remote_api.py``).  They now live inside
this package so they can be imported as ``mt5.<module>`` while keeping the
repository root tidy and easier to navigate.
"""

__all__ = [
    "auto_optimize",
    "backtest",
    "cli",
    "config_models",
    "config_schema",
    "crypto_utils",
    "eval_rl",
    "evolve_indicators",
    "evolve_symbols",
    "feature_store_cli",
    "focal_loss",
    "generate_signals",
    "grpc_api",
    "log_utils",
    "market_condition",
    "meta_train_nn",
    "metrics",
    "model_registry",
    "monitor_drift",
    "prediction_cache",
    "pretrain_contrastive",
    "pretrain_ts_encoder",
    "ray_stub",
    "ray_utils",
    "realtime_train",
    "regime",
    "risk_manager",
    "scheduler",
    "signal_queue",
    "state_manager",
    "strategy_dsl",
    "telemetry",
    "train",
    "train_allocator",
    "train_autogluon",
    "train_baseline",
    "train_cli",
    "train_combined",
    "train_ensemble",
    "train_graphnet",
    "train_meta",
    "train_nn",
    "train_online",
    "train_parallel",
    "train_price_distribution",
    "train_rl",
    "train_strategy",
    "train_utils",
    "user_risk_inputs",
    "walk_forward",
]
