//+------------------------------------------------------------------+
//|                                                  AdaptiveEA.mq5  |
//|                        Example Expert Advisor using ML signals   |
//+------------------------------------------------------------------+
#property copyright "OpenAI"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>
CTrade trade;

input string ModelSignalFile = "signals.csv"; // CSV generated by Python model
input double RiskPerTrade = 0.01;
input int TrailingStopPips = 20;

bool LoadSignal(datetime time, double &prob)
{
   int fh = FileOpen(ModelSignalFile, FILE_READ|FILE_CSV|FILE_ANSI);
   if(fh == INVALID_HANDLE)
      return(false);
   while(!FileIsEnding(fh))
   {
      datetime t = (datetime)FileReadString(fh);
      prob = FileReadNumber(fh);
      if(t == time)
      {
         FileClose(fh);
         return(true);
      }
   }
   FileClose(fh);
   return(false);
}

void OnTick()
{
   static datetime last_time=0;
   if(TimeCurrent()==last_time)
      return;
   last_time=TimeCurrent();

   double prob;
   if(!LoadSignal(TimeCurrent(), prob))
      return;

   if(PositionSelect(Symbol())==false && prob>0.55)
   {
      double volume=NormalizeDouble(AccountBalance()*RiskPerTrade/1000,2);
      trade.Buy(volume,NULL,Ask,0,0);
   }

   if(PositionSelect(Symbol()))
   {
      ulong ticket=PositionGetTicket(0);
      double stop=PositionGetDouble(POSITION_SL);
      double price=SymbolInfoDouble(Symbol(),SYMBOL_BID);
      double new_stop=price - TrailingStopPips*_Point;
      if(new_stop>stop)
         trade.PositionModify(ticket,new_stop,0);
   }
}
