# Configuration for Adaptive MT5 Bot
symbol: XAUUSD
symbols:
  - XAUUSD
  - GBPUSD
train_rows: 50000       # number of rows from CSV to use for training
threshold: 0.55        # probability threshold for taking a trade
trailing_stop_pips: 20
risk_per_trade: 0.01   # percentage of equity
max_daily_loss: 3.0    # percent
max_drawdown: 10.0     # percent
risk_lookback_bars: 50
use_sharpe_sizing: true
min_risk_factor: 0.5
max_risk_factor: 2.0
risk_var_lookback: 50
max_var: 5.0
max_stress_loss: 15.0
rsi_buy: 55            # RSI threshold for confirming entries
enable_news_trading: true
avoid_news_minutes: 5
data_urls:
  XAUUSD:
    - https://drive.google.com/uc?id=1FJ6NAcjMsGVFSKsCdvujL__rNin7bHcI
  GBPUSD:
    - https://drive.google.com/uc?id=1IHZvHtKONTVOqc_d0qOpQulDWE5e_xvQ
backtest_window_months: 6  # size of the training and test windows
backtest_step_months: 6    # months to advance for the next split
rl_steps: 5000            # PPO training steps
rl_max_position: 1.0      # max absolute position per symbol
rl_transaction_cost: 0.0001
rl_risk_penalty: 0.1      # weight for portfolio variance penalty
rl_var_window: 30         # lookback window for variance calculation

ensemble_models:
  - model.joblib
ensemble_method: bayesian
