avoid_news_minutes: 5
backtest_step_months: 6
backtest_window_months: 6
data_urls:
  GBPUSD:
    - https://drive.google.com/uc?id=1IHZvHtKONTVOqc_d0qOpQulDWE5e_xvQ
  XAUUSD:
    - https://drive.google.com/uc?id=1FJ6NAcjMsGVFSKsCdvujL__rNin7bHcI
api_history:
  GBPUSD:
    provider: mt5
    start: 2023-01-01
    end: 2025-01-01
  XAUUSD:
    provider: mt5
    start: 2023-01-01
    end: 2025-01-01
index_data:
  sp500: data/sp500.csv
  vix: data/vix.csv
enable_news_trading: true
ensemble_method: bayesian
ensemble_models:
- model.joblib
long_vol_period: 50
max_cvar: 7.5
max_daily_loss: 3.0
max_drawdown: 10.0
max_risk_factor: 2.0
max_stress_loss: 15.0
max_var: 5.0
min_risk_factor: 0.5
ray_num_cpus: 4
risk_lookback_bars: 50
risk_per_trade: 0.01
risk_var_lookback: 50
var_decay: 0.94
rl_max_position: 1.0
rl_risk_penalty: 0.1
rl_steps: 5000
rl_transaction_cost: 0.0001
rl_var_window: 30
rl_algorithm: PPO
rsi_buy: 55
short_vol_period: 10
symbol: XAUUSD
symbols:
- XAUUSD
- GBPUSD
threshold: 0.55
trailing_stop_pips: 20
train_rows: 50000
use_ray: false
parallel_backtest: true
use_scaler: true
use_sharpe_sizing: true

# enable or disable the ATR stop plugin
use_atr: true
# enable or disable the Donchian channel plugin
use_donchian: true
# enable FinBERT sentiment scoring
use_finbert_sentiment: false
# enable FinGPT sentiment scoring
use_fingpt_sentiment: false
# enable or disable the Keltner channel plugin
use_keltner: false
# enable Qlib technical factors
use_qlib_features: false
# enable or disable the HMM regime classifier plugin
use_regime_classifier: false
blend_with_rl: false
# risk check settings
use_spread_check: true
max_spread: 0.0005
use_slippage_check: true
max_slippage: 0.0005
