# Configuration for Adaptive MT5 Bot
symbol: XAUUSD
train_rows: 50000       # number of rows from CSV to use for training
threshold: 0.55        # probability threshold for taking a trade
trailing_stop_pips: 20
risk_per_trade: 0.01   # percentage of equity
max_daily_loss: 3.0    # percent
max_drawdown: 10.0     # percent
rsi_buy: 55            # RSI threshold for confirming entries
data_urls:
  XAUUSD:
    - https://drive.google.com/uc?id=1FJ6NAcjMsGVFSKsCdvujL__rNin7bHcI
  GBPUSD:
    - https://drive.google.com/uc?id=1IHZvHtKONTVOqc_d0qOpQulDWE5e_xvQ
