//+------------------------------------------------------------------+
//|                                                  RealtimeEA.mq5  |
//|      Example EA that loads model signals and auto-updates repo   |
//+------------------------------------------------------------------+
#property copyright "OpenAI"
#property version   "1.00"
#property strict

#include <Trade/Trade.mqh>
#import "shell32.dll"
int ShellExecuteW(int hwnd,string lpOperation,string lpFile,string lpParameters,string lpDirectory,int nShowCmd);
#import

CTrade trade;

input string RepoPath = "C:\\Path\\To\\TriangleBot\\MT5"; // local repo path
input string ModelSignalFile = "signals.csv"; // generated by Python
input double RiskPerTrade = 0.01;
input int TrailingStopPips = 20;

int OnInit()
{
   string cmd = StringFormat("/C git -C \"%s\" pull", RepoPath);
   ShellExecuteW(0, "open", "cmd.exe", cmd, NULL, 0);
   return(INIT_SUCCEEDED);
}

bool LoadSignal(datetime time,double &prob)
{
   int fh=FileOpen(ModelSignalFile,FILE_READ|FILE_CSV|FILE_ANSI);
   if(fh==INVALID_HANDLE)
      return(false);
   while(!FileIsEnding(fh))
   {
      datetime t=(datetime)FileReadString(fh);
      prob=FileReadNumber(fh);
      if(t==time)
      {
         FileClose(fh);
         return(true);
      }
   }
   FileClose(fh);
   return(false);
}

void OnTick()
{
   static datetime last_time=0;
   if(TimeCurrent()==last_time)
      return;
   last_time=TimeCurrent();

   double prob;
   if(!LoadSignal(TimeCurrent(),prob))
      return;

   if(!PositionSelect(Symbol()) && prob>0.55)
   {
      double volume=NormalizeDouble(AccountBalance()*RiskPerTrade/1000,2);
      trade.Buy(volume,NULL,Ask,0,0);
   }

   if(PositionSelect(Symbol()))
   {
      ulong ticket=PositionGetTicket(0);
      double stop=PositionGetDouble(POSITION_SL);
      double price=SymbolInfoDouble(Symbol(),SYMBOL_BID);
      double new_stop=price - TrailingStopPips*_Point;
      if(new_stop>stop)
         trade.PositionModify(ticket,new_stop,0);
   }
}
