apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt5-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mt5-bot
  template:
    metadata:
      labels:
        app: mt5-bot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
        - name: bot
          image: ghcr.io/youruser/mt5-bot:latest
          args: ["bash", "scripts/run_bot.sh"]
          ports:
            - containerPort: 8000
          env:
            - name: CONFIG_FILE
              value: "/opt/bot/config.yaml"
            - name: SIGNAL_QUEUE_URL
              value: "tcp://localhost:5555"
          livenessProbe:
            exec:
              command: ["python3", "scripts/healthcheck.py"]
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            exec:
              command: ["python3", "scripts/healthcheck.py"]
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - mountPath: /opt/mt5
              name: mt5-data
            - mountPath: /opt/bot/certs
              name: grpc-certs
              readOnly: true
      volumes:
        - name: mt5-data
          persistentVolumeClaim:
            claimName: mt5-pvc
        - name: grpc-certs
          secret:
            secretName: mt5-grpc-certs
