#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3-pip
  - python3-dev
  - build-essential
  - libzmq3-dev
  - git
  - wine
runcmd:
  - [bash, -lc, "git clone https://github.com/USERNAME/MT5.git /opt/MT5"]
  - [bash, -lc, "cd /opt/MT5 && pip3 install --upgrade pip && pip3 install -r requirements-core.txt"]
  - [bash, -lc, "/opt/MT5/scripts/install_service.sh"]
