#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3-pip
  - python3-dev
  - build-essential
  - git
  - wine
runcmd:
  - [bash, -lc, "git clone https://github.com/yegorsokolov/MT5.git /opt/MT5"]
  - [bash, -lc, "cd /opt/MT5 && ./scripts/setup_ubuntu.sh"]
