# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'config.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x06\x63onfig\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\nKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\":\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\x05\"I\n\rUpdateRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"2\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07version\x18\x02 \x01(\x05\x32\xc2\x01\n\rConfigService\x12\x34\n\tGetConfig\x12\x12.config.KeyRequest\x1a\x13.config.ConfigEntry\x12=\n\x0cUpdateConfig\x12\x15.config.UpdateRequest\x1a\x16.config.UpdateResponse\x12<\n\x0bWatchConfig\x12\x16.google.protobuf.Empty\x1a\x13.config.ConfigEntry0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KEYREQUEST']._serialized_start=53
  _globals['_KEYREQUEST']._serialized_end=78
  _globals['_CONFIGENTRY']._serialized_start=80
  _globals['_CONFIGENTRY']._serialized_end=138
  _globals['_UPDATEREQUEST']._serialized_start=140
  _globals['_UPDATEREQUEST']._serialized_end=213
  _globals['_UPDATERESPONSE']._serialized_start=215
  _globals['_UPDATERESPONSE']._serialized_end=265
  _globals['_CONFIGSERVICE']._serialized_start=268
  _globals['_CONFIGSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
