# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: management.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'management.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10management.proto\x12\nmanagement\"\x1e\n\x0cStartRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\"\x1e\n\x0c\x42otIdRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\" \n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"1\n\x10\x42otStatusRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\r\n\x05lines\x18\x02 \x01(\x05\"c\n\x11\x42otStatusResponse\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0f\n\x07running\x18\x02 \x01(\x08\x12\x0b\n\x03pid\x18\x03 \x01(\x05\x12\x12\n\nreturncode\x18\x04 \x01(\x05\x12\x0c\n\x04logs\x18\x05 \x01(\t\"\x1b\n\nLogRequest\x12\r\n\x05lines\x18\x01 \x01(\x05\"\x1b\n\x0bLogResponse\x12\x0c\n\x04logs\x18\x01 \x01(\t2\x9c\x02\n\x11ManagementService\x12@\n\x08StartBot\x12\x18.management.StartRequest\x1a\x1a.management.StatusResponse\x12?\n\x07StopBot\x12\x18.management.BotIdRequest\x1a\x1a.management.StatusResponse\x12H\n\tBotStatus\x12\x1c.management.BotStatusRequest\x1a\x1d.management.BotStatusResponse\x12:\n\x07GetLogs\x12\x16.management.LogRequest\x1a\x17.management.LogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTREQUEST']._serialized_start=32
  _globals['_STARTREQUEST']._serialized_end=62
  _globals['_BOTIDREQUEST']._serialized_start=64
  _globals['_BOTIDREQUEST']._serialized_end=94
  _globals['_STATUSRESPONSE']._serialized_start=96
  _globals['_STATUSRESPONSE']._serialized_end=128
  _globals['_BOTSTATUSREQUEST']._serialized_start=130
  _globals['_BOTSTATUSREQUEST']._serialized_end=179
  _globals['_BOTSTATUSRESPONSE']._serialized_start=181
  _globals['_BOTSTATUSRESPONSE']._serialized_end=280
  _globals['_LOGREQUEST']._serialized_start=282
  _globals['_LOGREQUEST']._serialized_end=309
  _globals['_LOGRESPONSE']._serialized_start=311
  _globals['_LOGRESPONSE']._serialized_end=338
  _globals['_MANAGEMENTSERVICE']._serialized_start=341
  _globals['_MANAGEMENTSERVICE']._serialized_end=625
# @@protoc_insertion_point(module_scope)
