#!/usr/bin/env bash
set -euo pipefail

# --------- SETTINGS ---------
export WINEARCH=win64
export WINEDEBUG=-all
MT5_PREFIX="$HOME/.wine-mt5"                # single prefix for MT5 + Windows-Python
REPO_SSH="git@github.com:yegorsokolov/MT5.git"
PROJ_DIR="$HOME/MT5"
WIN_PY_VER="3.11.9"
WIN_PY_EXE="python-${WIN_PY_VER}-amd64.exe"
WIN_PY_URL="https://www.python.org/ftp/python/${WIN_PY_VER}/${WIN_PY_EXE}"
MT5_SETUP_URL="https://download.mql5.com/cdn/web/metaquotes.software.corp/mt5/mt5setup.exe"
# ----------------------------

echo ">>> Cleanup"
cd "$HOME"
rm -rf "${MT5_PREFIX}" ~/.wine ~/.wine-py311 || true
sudo rm -rf /opt/mt5 || true
rm -rf "$PROJ_DIR" || true

echo ">>> Install Wine + helpers"
sudo dpkg --add-architecture i386 || true
sudo apt update
sudo apt install -y wine64 wine32:i386 winetricks cabextract wget unzip git python3-venv

echo ">>> Init Wine prefix: ${MT5_PREFIX}"
export WINEPREFIX="${MT5_PREFIX}"
wineboot --init

echo ">>> Install VC++ runtimes (UCRT etc.)"
winetricks -q vcrun2022 || true
# Force DLL overrides to native,builtin for UCRT & MSVC runtimes
cat > /tmp/dlloverrides.reg <<'REG'
REGEDIT4

[HKEY_CURRENT_USER\Software\Wine\DllOverrides]
"ucrtbase"="native,builtin"
"msvcp140"="native,builtin"
"vcruntime140"="native,builtin"
"vcruntime140_1"="native,builtin"
REG
wine regedit /S /tmp/dlloverrides.reg

echo ">>> Download and install MetaTrader 5"
sudo mkdir -p /opt/mt5 && sudo chown "$USER":"$USER" /opt/mt5
cd /opt/mt5
wget -O mt5setup.exe "${MT5_SETUP_URL}"
# GUI installer gives best results for first-time setup
wine mt5setup.exe || true

echo ">>> Start MT5 so you can log in (leave it running)"
wine "C:\\Program Files\\MetaTrader 5\\terminal64.exe" &>/dev/null &

echo ">>> Download and install Windows-Python ${WIN_PY_VER} in the SAME prefix"
cd /opt/mt5
wget -O "${WIN_PY_EXE}" "${WIN_PY_URL}"
wine "${WIN_PY_EXE}" /quiet InstallAllUsers=1 PrependPath=1 Include_pip=1
# Find Windows-Python in this prefix
WIN_PY=$(find "$WINEPREFIX/drive_c" -maxdepth 6 -type f -iname python.exe | grep -Ei 'Python3(1[01]|[0-9]+)/python.exe$' | head -n1)
if [[ -z "${WIN_PY}" ]]; then
  WIN_PY=$(find "$WINEPREFIX/drive_c" -maxdepth 6 -type f -iname python.exe | head -n1)
fi
if [[ -z "${WIN_PY}" ]]; then
  echo "Windows Python executable not found inside ${WINEPREFIX}" >&2
  exit 1
fi
WIN_PY_WINPATH=$(winepath -w "$WIN_PY")

echo ">>> Install MetaTrader5 (and pin NumPy for stability) inside Windows-Python"
wine "$WIN_PY_WINPATH" -m pip install --upgrade pip
wine "$WIN_PY_WINPATH" -m pip install "numpy<2.4" MetaTrader5

echo ">>> Clone your project via SSH"
cd "$HOME"
git clone "$REPO_SSH" "$PROJ_DIR"
cd "$PROJ_DIR"

echo ">>> Create Linux venv (prefer pyenv 3.11.9 if available)"
if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init - bash)" 2>/dev/null || true
  pyenv install -s 3.11.9
  pyenv local 3.11.9
  PY311=$(pyenv which python)
  "$PY311" -m venv .venv
else
  python3 -m venv .venv
fi
source .venv/bin/activate
python -V

echo ">>> Install Python deps (excluding MetaTrader5 which is Windows-only)"
if grep -qi '^MetaTrader5' requirements.txt; then
  grep -vi '^MetaTrader5' requirements.txt > requirements.nomt5.txt
  pip install --upgrade pip wheel setuptools
  pip install -r requirements.nomt5.txt
else
  pip install --upgrade pip wheel setuptools
  pip install -r requirements.txt
fi

echo ">>> Write .env with Wine/MT5 paths"
MT5_TERMINAL_WIN="C:\\Program Files\\MetaTrader 5\\terminal64.exe"
cat > .env <<EOF
# --- auto-generated by deploy_mt5.sh ---
WINEPREFIX=${MT5_PREFIX}
WINE_PYTHON="$(echo "$WIN_PY_WINPATH" | sed 's/\\\\/\\\\\\\\/g')"
MT5_TERMINAL_PATH="${MT5_TERMINAL_WIN}"
EOF

echo ">>> Install heartbeat script into MT5"
mkdir -p "$WINEPREFIX/drive_c/Program Files/MetaTrader 5/MQL5/Scripts"
if [ -d "scripts/MT5Bridge" ]; then
  cp -r scripts/MT5Bridge "$WINEPREFIX/drive_c/Program Files/MetaTrader 5/MQL5/Scripts/" || true
fi

echo
echo "### ACTION REQUIRED ###"
echo "1) In the MT5 window (already launched), log in to your broker and wait until it's connected."
echo "2) Then press ENTER here to continue."
read -r _

echo ">>> Run your Ubuntu setup script (now that MT5 is connected)"
bash scripts/setup_ubuntu.sh

echo ">>> Quick environment check"
python -m utils.environment || true

echo
echo "All done. Notes:"
echo "- Wine logs are suppressed via WINEDEBUG=-all (remove if you want verbose)."
echo "- If a future 'ucrtbase.crealf' appears, re-run: winetricks -q vcrun2022 and keep DLL overrides."

