name: Build Debian package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential devscripts debhelper
      - name: Build package
        run: dpkg-buildpackage -us -uc -b
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mt5bot-deb
          path: ../mt5bot_*.deb
      - name: Publish release asset
        uses: softprops/action-gh-release@v1
        with:
          files: ../mt5bot_*.deb
