name: docs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Build HTML
        run: sphinx-build -b html -W docs docs/_build/html
      - name: Run doctest
        run: sphinx-build -b doctest -W docs docs/_build/doctest
      - name: Upload docs artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: docs/_build/html
