name: Run tests

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'tests/**'
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff flake8 mypy
      - name: Run linters
        run: |
          ruff check .
          flake8 .

      - name: Run type checks
        run: mypy

      - name: Run quality checks and tests
        run: |
          python scripts/check_skeletons.py
          pytest -q
