name: Run tests

on:
  push:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'tests/**'
  pull_request:
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'tests/**'

jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install core and RL dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-core.txt
            pip install .[rl]

        - name: Verify pinned requirements
          run: |
            pip freeze | sort > requirements.lock
            cat requirements-core.txt requirements-rl.txt | sort > requirements.expected
            diff -u requirements.expected requirements.lock

        - name: Install linting and test tools
          run: |
            pip install .[test]
            pip install ruff flake8 mypy

        - name: Run linters and type checks
          run: |
            ruff check .
            flake8 .
            mypy .

        - name: Run quality checks and tests
          run: |
            python scripts/check_skeletons.py
            pytest -q
